---
# tasks file for molecule_showcase

- name: Ensure groups exists
  group:
    name: "{{ item.groups }}"
    state: present
  loop: "{{ users }}"

- name: Create user accounts
  user:
    name: "{{ item.username }}"
    groups: "{{ item.groups }}"
    password: "{{ lookup('password', './password.{{ item.username }} chars=ascii_lowercase,digits length=6') }}"
  loop: "{{ users }}"

- name: Ensure apache is present
  yum:
    name: httpd
    state: present

- name: Make sure a service is running
  service:
    state: started
    name: httpd
    enabled: true
