---
# tasks file for molecule-showcase

- name: Ensure groups exists
  group:
    name: "{{ item.groups }}"
    state: present
  loop: "{{ users }}"

- name: Create user accounts
  user:
    name: "{{ item.username }}"
    groups: "{{ item.groups }}"
  loop: "{{ users }}"

- name: Ensure apache is present
  yum:
    name: httpd
    state: present

- name: Make sure a service is running
  systemd:
    state: started
    name: httpd
