---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
#  - name: rhel8
#    image: registry.access.redhat.com/ubi8/ubi-init
#    tmpfs:
#      - /run
#      - /tmp
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro
#    capabilities:
#      - SYS_ADMIN
#    command: "/usr/sbin/init"
#    pre_build_image: true
  - name: instance
    image: geerlingguy/docker-centos8-ansible:latest
    command: ""
    volume:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
