---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - rhel8
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: |
          pip3 install molecule[podman] docker yamllint ansible-lint
          sudo apt-get update -qq
          sudo apt-get -qq -y install podman
          sudo mkdir -p /run/dbus
          sudo /etc/init.d/dbus start

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
